/*
Boost Software License - Version 1.0 - August 17th, 2003
 * Modified by Victor Rouquette - January 2017

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
 */

/* 
 * File:   FCore.cpp
 * Author: guillem
 *
 * Created on 27 janvier 2017, 11:47
 */

#include "Core/FCore.hpp"

FCore::FCore(   std::shared_ptr< FQueue< std::shared_ptr< FMessages > > > _pop_queue_parser, 
                std::shared_ptr< FQueue< std::shared_ptr< FMessages > > > _push_queue_parser,
                std::shared_ptr< FQueue< std::shared_ptr< FMessages > > > _pop_queue_render,
                std::shared_ptr< FQueue< std::shared_ptr< FMessages > > > _push_queue_render
             ):
              _m_pop_queue_parser(_pop_queue_parser),
              _m_push_queue_parser(_push_queue_parser),
              _m_pop_queue_render(_pop_queue_render),
              _m_push_queue_render(_push_queue_render)
              {

              }


/*
 * Thread that will manage  
 * the part of the memory 
 * containing the containers
 */

void FCore::thr_timestamps_manager(){
    std::shared_ptr<FMessages> msg_render = *(m_render_timestamps.try_pop() );

    if(msg_render != NULL){

        patternStruct received = *( std::static_pointer_cast<patternStruct>(msg_render->getContent() ) );

        float beginTime = received.tBegin;
        float endTime = received.tEnd;

        if( m_containers.at( received.contId )->contains( received ) ){ //is in memory
            if(isContainerFull(received.contId, beginTime, endTime)){
                patternStruct pattern_send = {received.id, received.contId, beginTime, endTime};
                std::shared_ptr<void> content_send = std::static_pointer_cast<void>( std::make_shared<patternStruct>(pattern_send) );
                FMessages msg_send(TIMESTAMP, content_send); 
                _m_push_queue_render->push( std::make_shared< FMessages >(msg_send) );
            }else{
                float endTimeLoaded = getContainerContent( received.contId, beginTime );
                patternStruct pattern_send = {received.id, received.contId, beginTime, endTimeLoaded};
                std::shared_ptr<void> content_send = std::static_pointer_cast<void>( std::make_shared<patternStruct>(pattern_send) );
                FMessages msg_send(TIMESTAMP, content_send); 
                _m_push_queue_render->push( std::make_shared< FMessages >(msg_send) );              
            }


        }else{ // is not in memory 
            _m_push_queue_parser->push( msg_render );
        }
    }

    std::shared_ptr< FMessages > msg_parser = *(m_parser_timestamps.try_pop() );
    if(msg_parser != NULL){

        patternStruct received = *( std::static_pointer_cast<patternStruct>(msg_render->getContent() ) );
        /*
        TODO
        */
    }
    
}


/*
 * Thread that will manage  
 * the part of the memory 
 * containing the occurrences
 */
void FCore::thr_occurrences_manager(){

    std::shared_ptr< FMessages > msg_render = *(m_render_occurrences.try_pop() );
    if(msg_render != NULL){
                if( m_occurrences.contains( msg_render->first 
                                    && m_occurrences.at( msg_render->first )->contains( msg_render->second ) ) 
                                  ){ /* is in memory */
            std::shared_ptr<FOccurrence> msg_send = m_occurrences.at( msg_render->first )->at( msg_render->second );
            _m_push_queue_render->push( msg_send );
        }else{ /* is not in memory */
            _m_push_queue_parser->push( msg_render );
        }
    }


    std::shared_ptr< FMessages > msg_parser = *(m_parser_occurrences.try_pop() );
    if(msg_parser != NULL){
        std::pair<int, int> key = std::make_pair( msg_parser->getPatternId(), msg_parser->getId() );
        std::pair<int, std::shared_ptr<FOccurrence> > my_pair = std::make_pair(key.second, msg_parser);
        m_occurrences.at(key.first)->insert( my_pair );
        _m_push_queue_render_occurrences->push(msg_parser);
    }

}


void FCore::thr_messages_handler_parser(){

    std::shared_ptr<FMessages> msg = _m_pop_queue_parser->wait_and_pop();
    if(msg != NULL){
        switch(msg->getHeader()){
            case(START):
            {

                break;
            }
            case(INITDONE):
            {

                break;
            }
            case(CONTAINER):
            {
                std::shared_ptr<FContainer> received = std::static_pointer_cast<FContainer>(msg->getContent());
                m_containers.insert( received->getId() , received );
                break;
            }
            case(PATTERN):
            {
                std::shared_ptr<FPattern> received = std::static_pointer_cast<FPattern>(msg->getContent());
                m_patterns.insert( received->getId(), received );
                break;
            }
            case(TIMESTAMP):
            {
                m_queue_timestamps.push( msg );
                break;
            }
            case(OCCURRENCE):
            {
                m_queue_occurrences.push( msg );
                break;
            }
            default:

            break;

        }
    }

}

void FCore::thr_messages_handler_renderer(){

    std::shared_ptr<FMessages> msg = _m_pop_queue_render->wait_and_pop();
    if(msg != NULL){
        switch(msg->getHeader()){
            case(START):
            {

                break;
            }
            case(INITDONE):
            {

                break;
            }
            case(CONTAINER):
            {

                break;
            }
            case(PATTERN):
            {

                break;
            }
            case(TIMESTAMP):
            {
                m_queue_timestamps.push( msg );
                break;
            }
            case(OCCURRENCE):
            {
                m_queue_occurrences.push( msg );
                break;
            }
            default:

            break;

        }
    }

}




void  FCore::check_memory(){
    if(m_occurrences.size() > MAX_SIZE){
        !m_occurrences.erase();
    }
   
    if(m_containers.size() > MAX_SIZE){
        !m_containers.erase();
    }
}

    
void FCore::thr_FCore(){
        
    //std::thread message_handler_parser_( [this]{thr_messages_handler_parser();} );
    //FThread_guard mhpp_g( message_handler_parser_ );
        
    std::thread container_manager_( [this]{thr_containers_manager();} );
    FThread_guard cm_g(container_manager_);
        
    std::thread occurrences_manager_( [this]{thr_occurrences_manager();} );
    FThread_guard om_g(occurrences_manager_);
        
    while(awake){
            
    } 
        
    //std::thread message_handler_renderer_( [this]{thr_messages_handler_renderer();} );
    //FThread_guard mhpr_g( message_handler_renderer_ );
    
    while(1){
        check_memory();
    } 
}

static std::vector<std::shared_ptr<FContainer> > view_containers(int a, int b){
    std::vector<std::shared_ptr<FContainer> > result;
    for(int i = a; i <= b; ++i){
        result.push_back( FCore::m_containers[i] );
    }
    return result;
}

static std::shared_ptr<FPattern>  view_patterns(int a){
    return FCore::m_patterns[a];
}


float FCore::getContainerContent(int id, float t1){
    bool isContinue = false;
    for(auto it = m_containers.at(id)->getPatternList().begin(); it != m_containers.at(id)->getPatternList().end(); ++it ){
        if( it->tBegin >= t1 ){
            auto it_tmp = it;
            ++it_tmp;
            if(it->tEnd <= it_tmp->tBegin + 0.01 || it->tEnd >= it_tmp->tBegin - 0.01){
                isContinue = true;
            }else{
                isContinue = false;
            }

            if(!isContinue){
                return it->tEnd;
            }
        }
    }

    return m_containers.at(id)->getPatternList().end()->tEnd;
}

bool FCore::isContainerFull(int id, float t1, float t2){
    bool isContinue = false;
    for(auto it = m_containers.at(id)->getPatternList().begin(); it != m_containers.at(id)->getPatternList().end(); ++it ){
        if( it->tBegin >= t1 ){
            auto it_tmp = it;
            ++it_tmp;
            if(it->tEnd <= it_tmp->tBegin + 0.01 || it->tEnd >= it_tmp->tBegin - 0.01){
                isContinue = true;
            }else{
                isContinue = false;
            }

            if(isContinue && it->tEnd >t2 ){
                return true;
            }
        }

        if( it->tBegin > t1 && it->tEnd > t2 ){
            return false;
        }
    }

    return false;
}