/*
Boost Software License - Version 1.0 - August 17th, 2003
 * Modified by Victor Rouquette - January 2017

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
 */

/* 
 * File:   FCore.hpp
 * Author: guillem
 *
 * Created on 24 janvier 2017, 15:38
 */

#ifndef FCORE_HPP
#define FCORE_HPP

#ifndef CORE_H
#define CORE_H

#define MAX_SIZE 200

#include <vector>

#include "thread_guard.h"
#include "threadsafe_list.h"
#include "threadsafe_hashmap.h"
#include "structures.h"

class FCore {
public:
    FCore( std::shared_ptr<FQueue> _pop_queue_parser, 
           std::shared_ptr<FQueue> _push_queue_parser,
           std::shared_ptr<FQueue> _pop_queue_renderer,
           std::shared_ptr<FQueue> _push_queue_renderer
           );
    
    FCore(const Core& orig);
    
    virtual ~FCore();
    
    void thr_FCore();
    
    
private:
    std::shared_ptr<FQueue> _m_pop_queue_parser;
    std::shared_ptr<FQueue> _m_push_queue_parser;
    std::shared_ptr<FQueue> _m_pop_queue_renderer;
    std::shared_ptr<FQueue> _m_push_queue_renderer;
     
    /*
     TODO
     */
    threadsafe_list<> m_renderer_occurrences;
    threadsafe_list<> m_renderer_container;
    threadsafe_list<> m_occurrences_renderer;
    threadsafe_list<> m_container_renderer;
    
    threadsafe_list<> m_parser_occurrences;
    threadsafe_list<> m_parser_container;
    threadsafe_list<> m_occurrences_parser;
    threadsafe_list<> m_container_parser;
    
    /*
     TODO
     */
    threadsafe_hashmap<std::pair<int, int>, std::shared_ptr<> > m_occurrences;
    threadsafe_hashmap<int, std::shared_ptr<> > m_container;
    threadsafe_hashmap<int, std::shared_ptr<> > m_patterns;
    
    void thr_threads_manager();
    void thr_occurrences_manager();
    
    void thr_message_handler_parser();
    void thr_message_handler_renderer();
    
    //check_memory ensure that the two map are not too big
    void check_memory();
};

    FCore::FCore( std::shared_ptr<FQueue> _pop_queue_parser, 
                  std::shared_ptr<FQueue> _push_queue_parser,
                  std::shared_ptr<FQueue> _pop_queue_renderer,
                  std::shared_ptr<FQueue> _push_queue_renderer):
                  _m_pop_queue_parser(_pop_queue_parser),
                  _m_pop_queue_parser(_push_queue_parser),
                  _m_pop_queue_parser(_pop_queue_parser),
                  _m_pop_queue_parser(_push_queue_parser)      
    {  
    }

    void FCore::thr_FCore(){
        std::thread threads_manager_( thr_threads_manager() );
        thread_guard tm_g(threads_manager_);
        std::thread occurrences_manager_( thr_occurrences_manager() );
        thread_guard om_g(occurrences_manager_);
    
    while(1){
        check_memory();
    } 
    }

#endif /* FCORE_HPP */

